### ISSUE TITLE
Search in a specific language

### ISSUE THREAD

**Issue by christophebe** [cravindra/pexels-api-wrapper#3]
Hello, 

Is it possible to make some search with the Pexel API in a specific language (french, spanish, ...).

Thanks

**Comment by cravindra** [comment]
Hello,

This library is just a wrapper around the [Official Pexels API](https://www.pexels.com/api/documentation/). You should be able to use this library to query in any language the API itself supports :) (I'm pretty sure the API supports this because the Pexels website itself is available in multiple languages)

I'm going to close this issue for now as there is nothing much we can do in terms of the wrapper implementation itself. Feel free to come back and comment here if you face any issues using this library to make queries in different languages!
